[general]
RemoteNickFormat="{NICK} ({BRIDGE}): "
PreserveThreading=true
# Show messages announcing when people arrive/leave remote channels

#[slack.example]
##Token to connect with the Slack API
##You'll have to use a test/api-token using a dedicated user and not a bot token.
##See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
#Token="${SLACK_EXAMPLE_TOKEN}" # real user

# Civic Tech

[slack.betanyc]
Token="${SLACK_BETANYC_TOKEN}" # real user: bridgebot-patcon

[slack.cfa]
Token="${SLACK_CFA_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.civictechfredericton]
Token="${SLACK_CIVICTECHFREDERICTON_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.civictechlondon]
Token="${SLACK_CIVICTECHLONDON_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.civictechsj]
Token="${SLACK_CIVICTECHSJ_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.civictechto]
Token="${SLACK_CIVICTECHTO_TOKEN}" # bot user
ShowJoinPart=true

[slack.civictechwr]
Token="${SLACK_CIVICTECHWR_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.civictechyvr]
Token="${SLACK_CIVICTECHYVR_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.codeforall]
Token="${SLACK_CODEFORALL_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.codeforberkeley]
Token="${SLACK_CODEFORBERKELEY_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.g0v-tw]
Token="${SLACK_G0VTW_TOKEN}" # real user: bridgebot-patcon
ShowJoinPart=true

[slack.openoakland]
Token="${SLACK_OPENOAKLAND_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.progressivehacknight]
Token="${SLACK_PROGHACKNIGHT_TOKEN}" # real user: bridgebot-patcon

[slack.sfbrigade]
Token="${SLACK_SFBRIGADE_TOKEN}" # real user: patcon
ShowJoinPart=true

[slack.yowcivictech]
Token="${SLACK_YOWCIVICTECH_TOKEN}" # real user: patcon
ShowJoinPart=true

# EDGI

[slack.archivers]
Token="${SLACK_ARCHIVERS_TOKEN}" # real user

[slack.edgi]
Token="${SLACK_EDGI_TOKEN}" # real user

# HackLab Toronto

[slack.diybioto]
Token="${SLACK_DIYBIOTO_TOKEN}" # TMP patcon user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[slack.hacklabto]
Token="${SLACK_HACKLABTO_TOKEN}" # bot user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[telegram.hacklabto]
Token="${TELEGRAM_TOKEN}" # bot user: hacklabto_bridgebot
RemoteNickFormat="{NICK}@{PROTOCOL}: "
UseInsecureURL=true

# Other

[slack.muckrock]
Token="${SLACK_MUCKROCK_TOKEN}" # matterbridge-bot user

[slack.opencollective]
Token="${SLACK_OPENCOLLECTIVE_TOKEN}" # real user

[slack.metapolis]
Token="${SLACK_METAPOLIS_TOKEN}" # real user: patcon

[gitter.gitter]
Token="${GITTER_BRIDGEBOT_TOKEN}" # bot user: gitterbridgebot twitter account
RemoteNickFormat="**{NICK}** ({PROTOCOL}): "

[irc.freenode]
Server="chat.freenode.net:6697"
Nick="${IRC_USERNAME}"
RemoteNickFormat="{NICK}@{PROTOCOL} "
UseTLS=true
UseSASL=true
NickServNick="${IRC_USERNAME}"
NickServPassword="${IRC_PASSWORD}"
IgnoreNicks="doorbot"

[[gateway]]
name="muckrock-canada"
enable=false
  [[gateway.inout]]
  account="slack.civictechto"
  channel="muckrock-canada-pub"
  [[gateway.inout]]
  account="slack.muckrock"
  channel="canada"

[[gateway]]
name="datatogether"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="datatogether"
  [[gateway.inout]]
  account="slack.archivers"
  channel="datatogether"

[[gateway]]
name="community-building"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="community_building"
  [[gateway.inout]]
  account="slack.archivers"
  channel="community-building"

[[gateway]]
name="webmonitoring"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="webmonitoring"
  [[gateway.inout]]
  account="slack.archivers"
  channel="webmonitoring"

[[gateway]]
name="oc-edgi"
enable=false # archived on EDGI side
  [[gateway.inout]]
  account="slack.edgi"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-edgi"

[[gateway]]
name="oc-civictechto"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="ctto-finances"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-civictechto"

## HACKLAB

[[gateway]]
name="hacklabto-general"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001087615555"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="general"

[[gateway]]
name="hacklabto-3d-printers"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001081652474"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="3d-printers"

[[gateway]]
name="hacklabto-amateur-radio"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="amateur_radio"

[[gateway]]
name="hacklabto-diybioto"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001089003630"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="biolab"
  [[gateway.inout]]
  account="slack.diybioto"
  channel="general"

[[gateway]]
name="hacklabto-darkroom"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="darkroom"

[[gateway]]
name="hacklabto-shop"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001093582611"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="shop"

[[gateway]]
name="hacklabto-board"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="hacklab-board"

[[gateway]]
name="hacklabto-operations"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001135498637"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="operations"

[[gateway]]
name="hacklabto-onboarding"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001317677382"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="onboarding"

[[gateway]]
name="opencollective-hacklabto"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-hacklabto"

[[gateway]]
name="hacklabto-irc"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="freenode-irc"
  [[gateway.inout]]
  account="irc.freenode"
  channel="#hacklabto"

[[gateway]]
name="lobby"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="public-lobby"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="hacklabto/lobby"

[[gateway]]
name="metapolis-gitter"
enable=true
  [[gateway.inout]]
  account="slack.metapolis"
  channel="gitter-general"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="polis-overview/Lobby"

[[gateway]]
name="civictechto-lobby"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="public-lobby"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/Lobby"

[[gateway]]
name="civictechto-speaker-questions"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="org-speaker-questions"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/speaker-questions"

[[gateway]]
name="organizing-canada"
enable=true
  [[gateway.inout]]
  account="slack.civictechfredericton"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.civictechlondon"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.civictechsj"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.civictechto"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.civictechwr"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.civictechyvr"
  channel="organizing-canada"
  [[gateway.inout]]
  account="slack.yowcivictech"
  channel="organizing-canada"

[[gateway]]
name="cira-grant-2018"
enable=true
  [[gateway.inout]]
  account="slack.yowcivictech"
  channel="cira-grant-2018"
  [[gateway.inout]]
  account="slack.civictechto"
  channel="cira-grant-2018"

# CodeAcross 2018

[[gateway]]
name="3rd-party-data"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="3rd-party-data"
  [[gateway.inout]]
  account="slack.yowcivictech"
  channel="3rd-party-data"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-3ptydata"

[[gateway]]
name="codeacross-c-commutng"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-commutng"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-commutng"

[[gateway]]
name="codeacross-c-jobtrnds"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-jobtrnds"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-jobtrnds"

[[gateway]]
name="codeacross-c-justice"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-justice"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-justice"

[[gateway]]
name="codeacross-c-library"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-library"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-library"

[[gateway]]
name="codeacross-c-parkdale"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-parkdale"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-parkdale"

[[gateway]]
name="codeacross-c-safework"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-safework"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-safework"

[[gateway]]
name="codeacross-c-students"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="codeacross-c-students"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="CivicTechTO/codeacross-c-students"

[[gateway]]
name="open-proj-experiment"
enable=false
  [[gateway.inout]]
  account="slack.civictechto"
  channel="open-proj-experiment"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="open-proj-experiment/Lobby"

[[gateway]]
name="news-intl"
enable=true
  [[gateway.inout]]
  account="slack.cfa"
  channel="news-intl"
  [[gateway.inout]]
  account="slack.civictechto"
  channel="news-intl"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="news"

[[gateway]]
name="oakland-berkeley"
enable=true
  [[gateway.inout]]
  account="slack.cfa"
  channel="oakland-berkeley"
  [[gateway.inout]]
  account="slack.codeforberkeley"
  channel="oakland-berkeley"
  [[gateway.inout]]
  account="slack.openoakland"
  channel="oakland-berkeley"

[[gateway]]
name="organizing-feed"
enable=true
  [[gateway.out]]
  account="slack.civictechto"
  channel="organizing-feed" # private: patcon-only

  [[gateway.in]]
  account="slack.civictechto"
  channel="organizing-open"
  [[gateway.in]]
  account="slack.civictechlondon"
  channel="organizing"
  [[gateway.in]]
  account="slack.civictechwr"
  channel="organizing"
  [[gateway.in]]
  account="slack.yowcivictech"
  channel="organizing"
  [[gateway.in]]
  account="slack.sfbrigade"
  channel="brigade"
  [[gateway.in]]
  account="slack.openoakland"
  channel="leadership"

[[samechannelgateway]]
  name="can-tw-relations"
  enable=true
  channels = [
    "bridge-testing",
    "rightscon-2018",
    "facilitation-fest-nyc",
  ]
  accounts = [
    "slack.civictechto",
    "slack.g0v-tw",
  ]
